// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jtlzhkrsuzcpkltdbmip.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp0bHpoa3JzdXpjcGtsdGRibWlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NDIwNjMsImV4cCI6MjA2NjQxODA2M30.EM4I0NDZ2GXwDxV4IB2MaSpMVFA2BFh48YA4yKXKbzQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);